create table if not exists public.rateio_historico_classificacoes (
  id bigint generated by default as identity primary key,
  titulo_origem_id bigint not null,
  competencia text not null,
  fornecedor text,
  historico text,
  observacao text,
  complemento text,
  categoria_codigo text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint rateio_historico_competencia_check
    check (competencia ~ '^(0[1-9]|1[0-2])/[0-9]{4}$'),
  constraint rateio_historico_categoria_codigo_check
    check (
      categoria_codigo in (
        'sem_rateio',
        'despesa_loja_assu',
        'despesa_loja_mossoro',
        'despesa_rateada_geral',
        'investimento_loja_assu',
        'investimento_loja_mossoro_centro',
        'despesa_comercial_me',
        'despesa_marilia',
        'despesa_extra_loja_assu',
        'despesa_extra_loja_mossoro',
        'despesa_loja_mossoro_partage',
        'investimento_loja_mossoro_partage',
        'despesa_rateada_entre_lojas_mossoro',
        'despesa_loja_avelloz_assu'
      )
    ),
  constraint rateio_historico_competencia_titulo_key
    unique (competencia, titulo_origem_id)
);

create index if not exists idx_rateio_historico_fornecedor
  on public.rateio_historico_classificacoes (fornecedor);

create index if not exists idx_rateio_historico_competencia
  on public.rateio_historico_classificacoes (competencia);

create or replace function public.set_rateio_historico_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_rateio_historico_updated_at
  on public.rateio_historico_classificacoes;

create trigger trg_rateio_historico_updated_at
before update on public.rateio_historico_classificacoes
for each row
execute function public.set_rateio_historico_updated_at();

-- Cria a primeira memoria do sistema com tudo que ja foi classificado.
-- Nao existe chave estrangeira de proposito: esta copia sobrevive quando
-- titulos_financeiros_pagos for limpa pela proxima importacao.
insert into public.rateio_historico_classificacoes (
  titulo_origem_id,
  competencia,
  fornecedor,
  historico,
  observacao,
  complemento,
  categoria_codigo
)
select
  classificacao.titulo_pago_id,
  classificacao.competencia,
  titulo.fornecedor,
  titulo.historico,
  titulo.observacao,
  titulo.complemento,
  classificacao.categoria_codigo
from public.titulo_pago_classificacoes as classificacao
inner join public.titulos_financeiros_pagos as titulo
  on titulo.id = classificacao.titulo_pago_id
on conflict (competencia, titulo_origem_id) do update set
  fornecedor = excluded.fornecedor,
  historico = excluded.historico,
  observacao = excluded.observacao,
  complemento = excluded.complemento,
  categoria_codigo = excluded.categoria_codigo;
